/**
 * withTVImageAssets.js
 *
 * Expo config plugin that copies the root Images.xcassets/ into
 * ios/tomotv/Images.xcassets/ during prebuild, overwriting the flat
 * single-layer assets generated by @react-native-tvos/config-tv with
 * proper multi-layer parallax icons produced by tvos-assets.
 *
 * MUST be listed AFTER @react-native-tvos/config-tv in app.json plugins.
 *
 * Created: January 29, 2026
 */

const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Recursively copy a directory, overwriting existing files.
 */
function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });

  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Expo config plugin to copy root Images.xcassets into the iOS project.
 * @param {Object} config - Expo config object
 * @returns {Object} Modified config object
 */
function withTVImageAssets(config) {
  return withDangerousMod(config, [
    "ios",
    async (config) => {
      // iOS (non-TV) builds keep the standard AppIcon.appiconset Expo generates from
      // icon.png; the tvOS brandassets parallax icons would clobber it.
      if (process.env.EXPO_TV !== "1") {
        console.log("[TVImageAssets] Skipped (non-TV build).");
        return config;
      }

      const projectRoot = config.modRequest.projectRoot;
      const projectName = config.modRequest.projectName;
      const src = path.join(projectRoot, "Images.xcassets");
      const dest = path.join(projectRoot, "ios", projectName, "Images.xcassets");

      console.log("\n[TVImageAssets] Copying multi-layer tvOS image assets...");

      if (!fs.existsSync(src)) {
        throw new Error(`[TVImageAssets] Source directory not found: ${src}\n` + "Run tvos-assets first to generate Images.xcassets.");
      }

      const topLevelEntries = fs.readdirSync(src);

      for (const entry of topLevelEntries) {
        const entrySrc = path.join(src, entry);
        const entryDest = path.join(dest, entry);

        if (fs.statSync(entrySrc).isDirectory()) {
          copyDirSync(entrySrc, entryDest);
        } else {
          fs.copyFileSync(entrySrc, entryDest);
        }

        console.log(`[TVImageAssets] ✓ ${entry}`);
      }

      console.log(`[TVImageAssets] Done — ${topLevelEntries.length} entries copied to ${dest}\n`);

      return config;
    },
  ]);
}

module.exports = withTVImageAssets;
