/**
 * The property CI enforces, checked here instead of only there.
 *
 * `constants/bundled-licenses.ts` is generated from whatever machine ran
 * `npm run licenses`, and the lookup used to be case-sensitive in effect: macOS
 * matched a file named `license` through the uppercase spelling and Linux did
 * not. A notice generated on Linux therefore moved 72 packages that DO ship a
 * license file into the declared-only list and dropped their copyright lines,
 * which is the failure the generator exists to prevent.
 *
 * These read the committed constant against node_modules on disk, so they fail
 * on a notice generated by a machine that could not see the files.
 */
import fs from "node:fs";
import path from "node:path";

import { BUNDLED_PACKAGES, BUNDLED_PACKAGES_DECLARED_ONLY } from "@/constants/bundled-licenses";

const ROOT = path.resolve(__dirname, "..", "..");
const LICENSE_FILE = /^(licen[cs]e|copying)/i;

const LOCK = JSON.parse(fs.readFileSync(path.join(ROOT, "package-lock.json"), "utf8")) as { packages: Record<string, { version?: string }> };

/**
 * Where a given VERSION actually lives. The hoisted node_modules/<name> is often
 * a different version — agent-base is 6.0.2 at the root and 7.1.4 under
 * metro-cache — so the lockfile key identifies the directory the notice was
 * built from. Only npm's path convention is borrowed, not the generator's rules
 * about which packages count.
 */
function packageDir(name: string, version: string): string | null {
  const suffix = `node_modules/${name}`;
  for (const [key, entry] of Object.entries(LOCK.packages)) {
    if (!key.endsWith(suffix) || entry.version !== version) continue;
    const dir = path.join(ROOT, key);
    if (fs.existsSync(dir)) return dir;
  }
  return null;
}

function licenseFiles(dir: string): string[] {
  return fs.readdirSync(dir).filter((entry) => LICENSE_FILE.test(entry));
}

describe("bundled licenses notice", () => {
  it("lists no package as declared-only while it ships a license file", () => {
    const wrong: string[] = [];
    for (const pkg of BUNDLED_PACKAGES_DECLARED_ONLY) {
      const dir = packageDir(pkg.name, pkg.version);
      if (!dir) continue;
      const files = licenseFiles(dir);
      if (files.length > 0) wrong.push(`${pkg.name} ships ${files.join(", ")} but is listed as declared-only`);
    }
    expect(wrong).toEqual([]);
  });

  it("attributes every package that ships a license file", () => {
    const missing: string[] = [];
    for (const pkg of BUNDLED_PACKAGES) {
      const dir = packageDir(pkg.name, pkg.version);
      if (!dir) continue;
      if (licenseFiles(dir).length === 0) missing.push(`${pkg.name} is attributed but ships no license file`);
    }
    expect(missing).toEqual([]);
  });

  it("keeps copyright lines on the package, never inside a shared body", () => {
    // A body is shared by up to 39 packages, so a copyright line inside one is
    // attributed to every package that shares it.
    const bodies = require("@/constants/bundled-licenses").BUNDLED_LICENSE_BODIES as Record<string, string>;
    const polluted = Object.entries(bodies)
      .filter(([, text]) => /^.*copyright\s*(\(c\)|©|\d{4}).*$/im.test(text))
      .map(([id]) => id);
    expect(polluted).toEqual([]);
  });
});
